source "https://rubygems.org"

gem "cucumber"
# gem "gherkin"
gem "rspec"
gem "rspec-expectations"
gem "capybara"
gem "selenium-webdriver"
gem "site_prism"
gem "syntax"
# gem "gmail", "0.4.0"
# gem "orderly"
gem "faker"
gem "activesupport"
# gem "rumouse"
# gem 'httparty', '~> 0.13.3'
# gem "chromedriver-helper"
# gem "parallel_tests"
# gem "capybara-screenshot"
# gem "pretty_face"
# gem "poltergeist"
# gem "send-keys"
# gem "json"
gem "sort"
gem "tiny_tds"
#gem "time_difference"
gem 'pry'