default: --format pretty --tags ~@wip --format json --out reports/dors_report<%= ENV['TEST_ENV_NUMBER'] %>.json -x --no-source DRIVER=debug
parallel:  scenarios --format pretty -x --format json --out reports/dors_report<%= ENV['TEST_ENV_NUMBER'] %>.json --format junit --out junit -t @pass
