Assessor:
 username: sudiv
 password: P@ssw0rd2

Compliance Manager:
 username: NGU_User
 password: P@ssw0rd1

Trainer1:
 username: newtrainer  #989797#
 password: P@s5w0rd1

Trainer2:
 username: roopa_setty1  #No Licences Added# (676767)
 password: P@s5w0rd2

Trainer3:
 username: trainer_3           #333111
 password: P@ssw0rd3

TrainerLicence:
 username: trainer_licence_agreement
 password: P@ssw0rd1

Trainer4:
 username: fabTrainer9  #888889# (P+T)
 password: P@s5w0rd1

Trainer5:
 username: trainer_status   #123896 (trainer login attempt failure) made it inactive rejected
 password: P@ssw0rd

Trainer6:
 username: trainer6     #to verify licence agree text
 password: P@s5w0rd6

Trainer7:
 username: roopa_licences    #131275
 password: P@s5w0rd7

Trainer8:
 username: test_prac_licences    #141386 only practical Licences
 password: P@s5w0rd8



Assessor1:
 username: johnny
 password: P@ssw0rd1

Assessor2:
  username: test_forces
  password: P@ssw0rd1

Assessor3:
  username: deena
  password: P@s5w0rd

Assessor4:
  username: chiefd       #No Assessments#
  password: Ch123456

#Assessor5:
#  username: test2auto
#  password: P@s6w0rd

Assessor5:
 username: test_assessor_status      #121212      testroopa1
 password: P@ssw0rd2

Assessor_Completed:
 username: Assessor_Completed
 password: P@ssw0rd1

#Note: #test738   #test tesxt#  no more exists in AD




LFU:
  username: SwapnaLFU    #LFU user on police portal#
  password: P@ssw0rd1

LFA:
  username: SwapnaLFA    #LFA user on police portal#
  password: P@ssw0rd1

LSU:
  username: SwapnaLSU    #LSU user on supplier portal#
  password: P@ssw0rd1

LSA:
  username: SwapnaLSA    #LSA user on supplier portal#
  password: P@ssw0rd1








