Assessor:
 trainer_licence_number: sudiv
 password: P@ssw0rd2

Compliance Manager:
 trainer_licence_number: NGU_User
 password: P@ssw0rd1

Trainer1:
 trainer_licence_number: newtrainer  #989797#
 password: P@s5w0rd1

Trainer2:
 trainer_licence_number: roopa_setty1  #No Licences Added# (676767)
 password: P@s5w0rd2

Trainer3:
 trainer_licence_number: trainer_3           #333111
 password: P@ssw0rd3

TrainerLicence:
 trainer_licence_number: trainer_licence_agreement
 password: P@ssw0rd1

Trainer4:
 trainer_licence_number: fabTrainer9  #888889# (P+T)
 password: P@s5w0rd1

Trainer5:
 trainer_licence_number: trainer_status   #123896 (trainer login attempt failure) made it inactive rejected
 password: P@ssw0rd

Trainer6:
 trainer_licence_number: trainer6     #to verify licence agree text
 password: P@s5w0rd6

Trainer7:
 trainer_licence_number: roopa_licences    #131275
 password: P@s5w0rd7

Trainer8:
 trainer_licence_number: test_prac_licences    #141386 only practical Licences
 password: P@s5w0rd8



Assessor1:
 trainer_licence_number: johnny
 password: P@ssw0rd1

Assessor2:
  trainer_licence_number: test_forces
  password: P@ssw0rd1

Assessor3:
  trainer_licence_number: deena
  password: P@s5w0rd

Assessor4:
  trainer_licence_number: chiefd       #No Assessments#
  password: Ch123456

#Assessor5:
#  trainer_licence_number: test2auto
#  password: P@s6w0rd

Assessor5:
 trainer_licence_number: test_assessor_status      #121212      testroopa1
 password: P@ssw0rd2

Assessor_Completed:
 trainer_licence_number: Assessor_Completed
 password: P@ssw0rd1

#Note: #test738   #test tesxt#  no more exists in AD




LFU:
  trainer_licence_number: SwapnaLFU    #LFU user on police portal#
  password: P@ssw0rd1

LFA:
  trainer_licence_number: SwapnaLFA    #LFA user on police portal#
  password: P@ssw0rd1

LSU:
  trainer_licence_number: SwapnaLSU    #LSU user on supplier portal#
  password: P@ssw0rd1

LSA:
  trainer_licence_number: SwapnaLSA    #LSA user on supplier portal#
  password: P@ssw0rd1








