Assessor:
 username: sudiv
 password: P@ssw0rd2

Compliance Manager:
 username: NGU_User
 password: P@ssw0rd1

Trainer1:
 username: newtrainer
 password: P@s5w0rd1

Trainer2:
 username: roopa_setty1  #No Licences Added#
 password: P@s5w0rd2

Trainer3:
 username: trainer3
 password: test@?12

Assessor1:
 username: johnny
 password: P@ssw0rd1

Assessor2:
  username: test_forces
  password: P@s5w0rd1

Assessor3:
  username: deena
  password: P@s5w0rd

Assessor4:
  username: chiefd    #No Assessments#
  password: Ch123456

Assessor5:
  username: test2auto
  password: P@ssw0rd5






LFU:
  username: SwapnaLFU    #LFU user on police portal#
  password: P@ssw0rd1

LFA:
  username: SwapnaLFA    #LFA user on police portal#
  password: P@ssw0rd1

LSU:
  username: SwapnaLSU    #LSU user on supplier portal#
  password: P@ssw0rd1

LSA:
  username: SwapnaLSA    #LSA user on supplier portal#
  password: P@ssw0rd1








