Assessor:
 username: sudiv
 password: P@ssw0rd2

Compliance Manager:
 username: NGU_User
 password: P@ssw0rd1

Trainer1:
 username: newtrainer
 password: P@s5w0rd1

Trainer2:
 username: roopa_setty1  #No Licences Added#
 password: P@s5w0rd2

Trainer3:
 username: trainer3
 password: P@s5w0rd3

Assessor1:
 username: johnny
 password: P@ssw0rd1

Assessor2:
  username: test_forces
  password: P@s5w0rd1

Assessor3:
  username: deena
  password: P@ssw0rd1

Assessor4:
  username: chiefd    #No Assessments#
  password: Ch123456

Assessor5:
  username: test2auto
  password: P@ssw0rd5








